environment:
  nodejs_version: "0.10"

branches:
  except:
    - gh-pages

skip_tags: true

version: 1.0.{build}

install:
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version) # Install-Product node $env:nodejs_version
  - npm install
  - npm install gulp -g

test_script:
  - node --version
  - npm --version
  - npm test

# build: off
build_script:
  - gulp

artifacts:
  - path: dist\\*
    name: dist-files

deploy:
#  - provider: GitHub
#    release: gbc-front-assets-v$(appveyor_build_version)
#    auth_token:
#      secure: XKA3cBKF7XTnVQoyoOHUa50A735FKx70E7jdGlNtkUtncJ+l0fQbveir6X7XSWpa
#    artifact: dist-files
#    on:
#      branch: master
      #appveyor_repo_tag: true
  - provider: S3
    access_key_id:
      secure: uGKkLWDE+5EHq5bGZI9UsK9mjrcaMJxdE6JGC4w5LAY=
    secret_access_key:
      secure: PBroBy13eeFE/m+7EklAwgM/KDWeVWr5L0yE4nIBx7KqBQd6jOgvU/lDeH4LEBvS
    bucket: static.guildford.gov.uk
    folder: assets
    artifact: dist-files
    set_public: true
    on:
      branch: master
      #appveyor_repo_tag: true
